### ISSUE TITLE
Translation Request: Japanese

### ISSUE THREAD

**Issue by lszxw1234** [denysdovhan/bash-handbook#96] opened 2019-07-08 06:50 UTC
I am able to translate this language [yes/no] Yes.

**Comment by denysdovhan** [comment] 2019-07-08 08:41
Duplicate of #89

**Comment by denysdovhan** [comment] 2019-07-08 08:41
Duplicate of #92

**Comment by denysdovhan** [comment] 2019-07-08 08:42
@lszxw1234 waiting for your PR. Closing this in favor of #89

**Closed by denysdovhan** 2019-07-08 08:42 UTC
Labels: propose
